language: R
sudo: false
cache: packages
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
  - stage: R CMD check
    r: oldrel
  - r: release
  - r: devel
